DROP TABLE IF EXISTS IM_ROLE_NAME_MST CASCADE;
DROP TABLE IF EXISTS IM_TITLE_NAME_MST CASCADE;
DROP TABLE IF EXISTS IM_ORG_NAME_MST CASCADE;
DROP TABLE IF EXISTS IM_COMPANY_NAME_MST CASCADE;
DROP TABLE IF EXISTS IM_USER_NAME_MST CASCADE;
DROP TABLE IF EXISTS IM_CONDITION CASCADE;
DROP TABLE IF EXISTS IM_ACTION CASCADE;
DROP TABLE IF EXISTS IM_RESOURCE CASCADE;
DROP TABLE IF EXISTS IM_SUBJECT CASCADE;
DROP TABLE IF EXISTS IM_RULE CASCADE;
DROP TABLE IF EXISTS IM_POLICY CASCADE;
DROP TABLE IF EXISTS IM_PASSWORD_POLICY CASCADE;
DROP TABLE IF EXISTS IM_LOGIN_POLICY CASCADE;
DROP TABLE IF EXISTS IM_USER_LOGIN_INFO CASCADE;
DROP TABLE IF EXISTS IM_LOGIN_CONTROL_INFO CASCADE;
DROP TABLE IF EXISTS IM_PASSWORD_HISTORY CASCADE;
DROP TABLE IF EXISTS IM_PASSWORD CASCADE;
DROP TABLE IF EXISTS IM_POSITION_ROLE CASCADE;
DROP TABLE IF EXISTS IM_ROLE_MST CASCADE;
DROP TABLE IF EXISTS IM_AGENT CASCADE;
DROP TABLE IF EXISTS IM_POSITION CASCADE;
DROP TABLE IF EXISTS IM_TITLE_MST CASCADE;
DROP TABLE IF EXISTS IM_ORG_HIERARCHY CASCADE;
DROP TABLE IF EXISTS IM_ORG_MST CASCADE;
DROP TABLE IF EXISTS IM_COMPANY_MST CASCADE;
DROP TABLE IF EXISTS IM_USER_MST CASCADE;


CREATE TABLE IM_USER_MST
(
  USER_ID                VARCHAR(50) PRIMARY KEY,
  USER_CODE              VARCHAR(50) NOT NULL,
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  USER_NAME              VARCHAR(50),
  MAIL                   VARCHAR(100),
  TEL                    VARCHAR(15),
  FAX                    VARCHAR(15),
  LOCALE                 VARCHAR(20),
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_COMPANY_MST
(
  COMPANY_ID             VARCHAR(50) PRIMARY KEY,
  COMPANY_CODE           VARCHAR(50) NOT NULL,
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  COMPANY_NAME           VARCHAR(50),
  COMPANY_TYPE           VARCHAR(50),
  COMPANY_COMMENT        VARCHAR(200),
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_ORG_MST
(
  ORG_ID                 VARCHAR(50) PRIMARY KEY,
  ORG_CODE               VARCHAR(50) NOT NULL,
  COMPANY_ID             VARCHAR(50),
  GROUP_FLG              DECIMAL(1),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  ORG_NAME               VARCHAR(50),
  ORG_TYPE               VARCHAR(50),
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_ORG_HIERARCHY
(
  HIERARCHY_ID           VARCHAR(50) PRIMARY KEY,
  HIERARCHY_CODE         VARCHAR(50) NOT NULL,
  ORG_ID                 VARCHAR(50),
  HIGH_ORG_ID            VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_TITLE_MST
(
  TITLE_ID               VARCHAR(50) PRIMARY KEY,
  TITLE_CODE             VARCHAR(50) NOT NULL,
  COMPANY_ID             VARCHAR(50),
  GROUP_FLG              DECIMAL(1),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  TITLE_NAME             VARCHAR(50),
  TITLE_TYPE             VARCHAR(50),
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_POSITION
(
  POSITION_ID            VARCHAR(50) PRIMARY KEY,
  POSITION_CODE          VARCHAR(50) NOT NULL,
  USER_ID                VARCHAR(50),
  ORG_ID                 VARCHAR(50),
  TITLE_ID               VARCHAR(50),
  CONCURRENT_FLG         DECIMAL(1),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_AGENT
(
  AGENT_ID               VARCHAR(50) PRIMARY KEY,
  AGENT_CODE             VARCHAR(50) NOT NULL,
  POSITION_ID            VARCHAR(50),
  AGENTED_POSITION_ID    VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_ROLE_MST
(
  ROLE_ID                VARCHAR(50) PRIMARY KEY,
  ROLE_CODE              VARCHAR(50) NOT NULL,
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  ROLE_NAME              VARCHAR(50),
  ROLE_TYPE              VARCHAR(50),
  ROLE_COMMENT           VARCHAR(200),
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_POSITION_ROLE
(
  POSITION_ROLE_ID            VARCHAR(50) PRIMARY KEY,
  POSITION_ROLE_CODE          VARCHAR(50) NOT NULL,
  POSITION_ID                 VARCHAR(50),
  ROLE_ID                     VARCHAR(50),
  ACTIVE_START_TIME           TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME             TIMESTAMP WITH TIME ZONE,
  CREATED_TIME                TIMESTAMP WITH TIME ZONE,
  CREATED_USER                VARCHAR(50),
  UPDATED_TIME                TIMESTAMP WITH TIME ZONE,
  UPDATED_USER                VARCHAR(50),
  DELETED_FLG                 DECIMAL(1),
  VERSION_NO                  DECIMAL(8)
)
;

CREATE TABLE IM_PASSWORD
(
  LOGIN_ID                    VARCHAR(20),
  COMPANY_CODE                VARCHAR(50),
  PASSWORD                    VARCHAR(100),
  PASSWORD_CHANGED_TIME       TIMESTAMP WITH TIME ZONE,
  PASSWORD_CHANGED_USER       VARCHAR(50),
  PASSWORD_MUST_CHANGE_FLG    DECIMAL(1),
  PRIMARY KEY(LOGIN_ID,COMPANY_CODE)
)
;

CREATE TABLE IM_PASSWORD_HISTORY
(
  LOGIN_ID                    VARCHAR(20),
  COMPANY_CODE                VARCHAR(50),
  VERSION_NO                  DECIMAL(8),
  PASSWORD_HISTORY            VARCHAR(100),
  PASSWORD_CHANGED_TIME       TIMESTAMP WITH TIME ZONE,
  PASSWORD_CHANGED_USER       VARCHAR(50),
  CREATED_TIME                TIMESTAMP WITH TIME ZONE,
  CREATED_USER                VARCHAR(50),
  PRIMARY KEY(LOGIN_ID,COMPANY_CODE,VERSION_NO)
)
;

CREATE TABLE IM_LOGIN_CONTROL_INFO
(
  LOGIN_ID                    VARCHAR(20),
  COMPANY_CODE                VARCHAR(50),
  ACCOUNT_INACTIVE_FLG        DECIMAL(1),
  ACCOUNT_ACTIVE_START_TIME   TIMESTAMP WITH TIME ZONE,
  ACCOUNT_ACTIVE_END_TIME     TIMESTAMP WITH TIME ZONE,
  PASSWORD_FAILURE_COUNT      DECIMAL(2),
  PASSWORD_FAILURE_RESET_TIME TIMESTAMP WITH TIME ZONE,
  LOCKOUT_END_TIME            TIMESTAMP WITH TIME ZONE,
  LAST_LOGIN_TIME             TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(LOGIN_ID,COMPANY_CODE)
)
;

CREATE TABLE IM_USER_LOGIN_INFO
(
  USER_LOGIN_INFO_ID          VARCHAR(50) PRIMARY KEY,
  USER_LOGIN_INFO_CODE        VARCHAR(50) NOT NULL,
  USER_ID                     VARCHAR(50),
  LOGIN_ID                    VARCHAR(20),
  COMPANY_CODE                VARCHAR(50),
  ACTIVE_START_TIME           TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME             TIMESTAMP WITH TIME ZONE,
  CREATED_TIME                TIMESTAMP WITH TIME ZONE,
  CREATED_USER                VARCHAR(50),
  UPDATED_TIME                TIMESTAMP WITH TIME ZONE,
  UPDATED_USER                VARCHAR(50),
  DELETED_FLG                 DECIMAL(1),
  VERSION_NO                  DECIMAL(8)
)
;

CREATE TABLE IM_LOGIN_POLICY
(
  LOGIN_POLICY_ID             VARCHAR(50) PRIMARY KEY,
  LOGIN_POLICY_CODE           VARCHAR(50) NOT NULL,
  COMPANY_CODE                VARCHAR(50),
  ACTIVE_START_TIME           TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME             TIMESTAMP WITH TIME ZONE,
  PASSWORD_EXPIRE_TERM        DECIMAL(8),
  PASSWORD_MAX_FAILURE        DECIMAL(2),
  PASSWORD_FAILURE_RESET_TERM DECIMAL(8),
  LOCKOUT_TERM                DECIMAL(8),
  MAX_SESSION_LIMIT           DECIMAL(10),
  PERMIT_TIME                 VARCHAR(100),
  PERMIT_DOMAIN               VARCHAR(200),
  CREATED_TIME                TIMESTAMP WITH TIME ZONE,
  CREATED_USER                VARCHAR(50),
  UPDATED_TIME                TIMESTAMP WITH TIME ZONE,
  UPDATED_USER                VARCHAR(50),
  DELETED_FLG                 DECIMAL(1),
  VERSION_NO                  DECIMAL(8)
)
;

CREATE TABLE IM_PASSWORD_POLICY
(
  PASSWORD_POLICY_ID          VARCHAR(50) PRIMARY KEY,
  PASSWORD_POLICY_CODE        VARCHAR(50) NOT NULL,
  COMPANY_CODE                VARCHAR(50),
  ACTIVE_START_TIME           TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME             TIMESTAMP WITH TIME ZONE,
  PASSWORD_MIN_LENGTH         DECIMAL(2),
  PASSWORD_LETTER_TYPE        VARCHAR(50),
  PASSWORD_MIN_LETTER_TYPE    DECIMAL(1),
  PASSWORD_IN_HISTORY         DECIMAL(2),
  CREATED_TIME                TIMESTAMP WITH TIME ZONE,
  CREATED_USER                VARCHAR(50),
  UPDATED_TIME                TIMESTAMP WITH TIME ZONE,
  UPDATED_USER                VARCHAR(50),
  DELETED_FLG                 DECIMAL(1),
  VERSION_NO                  DECIMAL(8)
)
;


CREATE TABLE IM_USER_NAME_MST
(
  USER_NAME_ID           VARCHAR(50) PRIMARY KEY,
  USER_ID                VARCHAR(50) NOT NULL,
  LOCALE                 VARCHAR(20) NOT NULL,
  USER_NAME              VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_COMPANY_NAME_MST
(
  COMPANY_NAME_ID        VARCHAR(50) PRIMARY KEY,
  COMPANY_ID             VARCHAR(50) NOT NULL,
  LOCALE                 VARCHAR(20) NOT NULL,
  COMPANY_NAME           VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_ORG_NAME_MST
(
  ORG_NAME_ID            VARCHAR(50) PRIMARY KEY,
  ORG_ID                 VARCHAR(50) NOT NULL,
  LOCALE                 VARCHAR(20) NOT NULL,
  ORG_NAME               VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_TITLE_NAME_MST
(
  TITLE_NAME_ID          VARCHAR(50) PRIMARY KEY,
  TITLE_ID               VARCHAR(50) NOT NULL,
  LOCALE                 VARCHAR(20) NOT NULL,
  TITLE_NAME             VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

CREATE TABLE IM_ROLE_NAME_MST
(
  ROLE_NAME_ID           VARCHAR(50) PRIMARY KEY,
  ROLE_ID                VARCHAR(50) NOT NULL,
  LOCALE                 VARCHAR(20) NOT NULL,
  ROLE_NAME              VARCHAR(50),
  ACTIVE_START_TIME      TIMESTAMP WITH TIME ZONE,
  ACTIVE_END_TIME        TIMESTAMP WITH TIME ZONE,
  CREATED_TIME           TIMESTAMP WITH TIME ZONE,
  CREATED_USER           VARCHAR(50),
  UPDATED_TIME           TIMESTAMP WITH TIME ZONE,
  UPDATED_USER           VARCHAR(50),
  DELETED_FLG            DECIMAL(1),
  VERSION_NO             DECIMAL(8)
)
;

DROP SEQUENCE IF EXISTS IM_ROLE_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_ROLE_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_ROLE_NAME_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_ROLE_NAME_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_POSITION_ROLE_SERIAL_TABLE;
CREATE SEQUENCE IM_POSITION_ROLE_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_CONDITION_SERIAL_TABLE;
CREATE SEQUENCE IM_CONDITION_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_ACTION_SERIAL_TABLE;
CREATE SEQUENCE IM_ACTION_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_RESOURCE_SERIAL_TABLE;
CREATE SEQUENCE IM_RESOURCE_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_SUBJECT_SERIAL_TABLE;
CREATE SEQUENCE IM_SUBJECT_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_RULE_SERIAL_TABLE;
CREATE SEQUENCE IM_RULE_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_POLICY_SERIAL_TABLE;
CREATE SEQUENCE IM_POLICY_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_LOGIN_POLICY_SERIAL_TABLE;
CREATE SEQUENCE IM_LOGIN_POLICY_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_PASSWORD_POLICY_SERIAL_TABLE;
CREATE SEQUENCE IM_PASSWORD_POLICY_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_USER_LOGIN_INFO_SERIAL_TABLE;
CREATE SEQUENCE IM_USER_LOGIN_INFO_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_COMPANY_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_COMPANY_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_AGENT_SERIAL_TABLE;
CREATE SEQUENCE IM_AGENT_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_COMPANY_NAME_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_COMPANY_NAME_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_ORG_HIERARCHY_SERIAL_TABLE;
CREATE SEQUENCE IM_ORG_HIERARCHY_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_ORG_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_ORG_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_ORG_NAME_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_ORG_NAME_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_POSITION_SERIAL_TABLE;
CREATE SEQUENCE IM_POSITION_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_TITLE_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_TITLE_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_TITLE_NAME_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_TITLE_NAME_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_USER_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_USER_MST_SERIAL_TABLE START WITH 1;

DROP SEQUENCE IF EXISTS IM_USER_NAME_MST_SERIAL_TABLE;
CREATE SEQUENCE IM_USER_NAME_MST_SERIAL_TABLE START WITH 1;

commit
;

